[project]
name = "webrtc-tools"
version = "0.1.2"
description = "一系列 WebRTC 调试工具"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flet>=0.28.3",
]

[dependency-groups]
dev = [
    "flet[all]>=0.28.3",
    "pyinstaller>=6.11.1",
]
